<footer>
	<img src="images/2015twd-compass-website-icon-info.png" class="footer-img info" alt="BCIT TWD Short Info Icon" /><span>For more Info</span>
	<a href="http://www.bcit.ca/"><img src="images/2015twd-compass-website-icon-BCIT.png" class="footer-img logo" alt="BCIT Logo" /></a>
	<div class="website-description">
		<p>TWD website is a central hub directory made for currently enrolled students, perspective students, parents, guidance counselor, and faculty. The purpose is to compile important information that the users may need such as program information, class schedule, current projects for marking, past projects for reference, and faculty support.</p>
		<p>If you wish to explore other BCIT opportunities, please click on the BCIT logo to start planning your future.</p>
		<p><span>British Columbia Institute of Technology</span>
		   <span>3700 Willingdon Avenue</span>
		   <span>Burnaby, British Columbia</span>
		   <span>Canada, V5G 3H2</span></p>
		<p><span>Telephone: 604-434-5734</span><p>
		<p><span>Toll-free (Can/US): 1-866-434-1610</span></p>
		<a href="http://www.bcit.ca/contacts/"><span>More Contact Numbers</span></a>
	</div>
</footer>

<script src="scripts/jquery-1.11.2.min.js"></script>
<script src="scripts/scripts.js"></script>
</body>
</html>